# Generated by Django 2.0.5 on 2018-05-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField()),
            ],
            options={
                'ordering': ('-last_modified', '-created'),
                'abstract': False,
            },
        ),
    ]
