# Generated by Django 2.0.5 on 2018-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlocation',
            name='id',
        ),
        migrations.AddField(
            model_name='shortenedlocation',
            name='identifier',
            field=models.PositiveIntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
